# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on: [push, pull_request]

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[tests] coveralls

    - name: PyTest
      run: |
        pytest --cov deepcell_retinamask --pep8

    - name: Coveralls
      if: env.COVERALLS_REPO_TOKEN != null
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        COVERALLS_FLAG_NAME: python-${{ matrix.python-version }}
        COVERALLS_PARALLEL: true
      run: |
        coveralls

  coveralls:
    name: Finish Coveralls
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      if: env.COVERALLS_REPO_TOKEN != null
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
